server:
  port: 8888
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/local?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 73699rxy