server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 73699rxy
  thymeleaf:
    mode: html5
    cache: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true